
openapi: 3.0.4
info:
  title: Tasks API
  description: 'This service sequences and orchestrates various tasks for an application'
  version: v1
servers:
  - url: https://dev.abc.com
    description: dev environment
  - url: https://test.abc.com
    description: test environment
  - url: https://abc.com
    description: production environment
paths:
  /tasks:
    post:
      tags:
        - create-tasks
      summary: Endpoint to create tasks
      description: Creates a list of tasks for a given application
      operationId: createTasks
      parameters:
        - name: requestHeaders
          in: header
          description: Request headers
          schema:
            allOf:
              - $ref: '#/components/schemas/requestHeaders'
          explode: true
          style: simple
        - name: x-request-id
          in: header
          required: true
          schema:
            maxLength: 36
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            type: string
            description: Must be in UUID v4 format.
            format: uuid
        - name: x-staff-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id-type
          in: header
          schema:
            $ref: '#/components/schemas/xUserIdType'
      requestBody:
        description: Task creation request
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/createTasksRequest'
              description: Request model for Task creation
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createTasksResponse'
        '500':
          description: Internal Server Error
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
  '/tasks/{task_id}':
    get:
      tags:
        - get-task
      summary: Endpoint to get a task by id
      description: Retrieves a single task by task id.
      operationId: getTask
      parameters:
        - name: task_id
          in: path
          description: Task Id
          required: true
          schema:
            type: string
        - name: requestHeaders
          in: header
          description: Request Headers
          schema:
            allOf:
              - $ref: '#/components/schemas/requestHeaders'
          explode: true
          style: simple
        - name: x-request-id
          in: header
          required: true
          schema:
            maxLength: 36
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            type: string
            description: Must be in UUID v4 format.
            format: uuid
        - name: x-staff-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id-type
          in: header
          schema:
            $ref: '#/components/schemas/xUserIdType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taskResponse'
        '500':
          description: Internal Server Error
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
    put:
      tags:
        - update-task
      summary: Endpoint to update a task
      description: Updates a task for a given application
      operationId: updateTask
      parameters:
        - name: task_id
          in: path
          description: Task Id
          required: true
          schema:
            type: string
        - name: requestHeaders
          in: header
          description: Request Headers
          schema:
            allOf:
              - $ref: '#/components/schemas/requestHeaders'
          explode: true
          style: simple
        - name: x-request-id
          in: header
          required: true
          schema:
            maxLength: 36
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            type: string
            description: Must be in UUID v4 format.
            format: uuid
        - name: x-staff-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id-type
          in: header
          schema:
            $ref: '#/components/schemas/xUserIdType'
      requestBody:
        description: Update task request
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/updateTaskRequest'
              description: Request model for updating task
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taskResponse'
        '500':
          description: Internal Server Error
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
    delete:
      tags:
        - delete-task
      summary: Endpoint to delete a task from an application
      description: Deletes an existing task for a given an application id.
      operationId: deleteTask
      parameters:
        - name: task_id
          in: path
          description: Task Id
          required: true
          schema:
            type: string
        - name: applicationNumber
          in: query
          description: Application number
          required: true
          schema:
            type: string
        - name: requestHeaders
          in: header
          description: Request Headers
          schema:
            allOf:
              - $ref: '#/components/schemas/requestHeaders'
          explode: true
          style: simple
        - name: x-request-id
          in: header
          required: true
          schema:
            maxLength: 36
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            type: string
            description: Must be in UUID v4 format.
            format: uuid
        - name: x-staff-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id
          in: header
          schema:
            maxLength: 10
            pattern: '^[0-9]{1,10}$'
            type: string
            format: string
        - name: x-user-id-type
          in: header
          schema:
            $ref: '#/components/schemas/xUserIdType'
      responses:
        '204':
          description: No Content
        '500':
          description: Internal Server Error
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problemDetails'
components:
  schemas:
    additionalDocumentsDetails:
      type: object
      properties:
        documentTypeIds:
          type: array
          items:
            type: string
          description: List of DocumentTypeIds
        reason:
          type: string
          description: Free text for reason
      additionalProperties: { }
      description: Additional Documents Details
    createTask:
      required:
        - category
        - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          description: Type of the task
        category:
          minLength: 1
          type: string
          description: Category of the task
        subCategory:
          type: string
          description: SubCategory of the task
          nullable: true
        additionalSubCategory:
          type: string
          description: Additional Subcategories for Verification Subcategories
          nullable: true
        linkedApplicationEntityId:
          type: string
          description: Linked Application Entity Id of the task
          nullable: true
        hold:
          allOf:
            - $ref: '#/components/schemas/createTaskFraudHold'
          description: Fraud hold details - Fraud type tasks only
          nullable: true
        outcome:
          type: string
          description: Task outcome for Verification tasks
          nullable: true
        liabilityDeletionReason:
          type: string
          description: Liability deletion reason
          nullable: true
        suppressCustomerTask:
          type: boolean
          description: Flag to indicate if customer task creation not required for a verification task
      additionalProperties: { }
      description: Model for Task data type
    createTaskFraudHold:
      type: object
      properties:
        durationInMinutes:
          type: integer
          description: Duration of hold in Minutes
          format: int32
        autoCloseAction:
          type: string
          description: Action to be performed after lapsing DurationInMinutes
          nullable: true
      additionalProperties: { }
      description: Fraud hold details
    createTaskResponse:
      type: object
      properties:
        id:
          type: string
          description: Id of the task
        type:
          type: string
          description: Type of the task
        category:
          type: string
          description: Category of the task
        subCategory:
          type: string
          description: Subcategory of the task
          nullable: true
        additionalSubCategory:
          type: string
          description: Additional Subcategory for Verification Tasks
          nullable: true
        linkedApplicationEntityId:
          type: string
          description: Linked entity Id within the application
          nullable: true
        state:
          type: string
          description: State of the task
        hold:
          allOf:
            - $ref: '#/components/schemas/createTaskFraudHold'
          description: Fraud hold details
          nullable: true
      additionalProperties: { }
      description: DTO for create task response
    createTasksRequest:
      required:
        - applicationNumber
        - tasks
      type: object
      properties:
        applicationNumber:
          minLength: 1
          type: string
          description: Application Number
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/createTask'
          description: List of tasks to be created
      additionalProperties: { }
      description: Request model for Task creation
    createTasksResponse:
      type: object
      properties:
        applicationNumber:
          type: string
          description: Application Number
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/createTaskResponse'
          description: Associated tasks with the application Id
      additionalProperties: { }
      description: Response model for Create task
    fraudHold:
      type: object
      properties:
        durationInMinutes:
          type: integer
          description: Duration of hold in Minutes
          format: int32
        autoCloseAction:
          type: string
          description: Action to be performed after lapsing DurationInMinutes
          nullable: true
      additionalProperties: { }
      description: Fraud hold details
    problemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
    requestHeaders:
      type: object
      properties:
        requestId:
          type: string
        userId:
          type: string
        userIdType:
          type: string
        staffId:
          type: string
          nullable: true
      additionalProperties: { }
    taskResponse:
      type: object
      properties:
        id:
          type: string
          description: Id of the task
        type:
          type: string
          description: Type of the task
        category:
          type: string
          description: Category of the task
        subCategory:
          type: string
          description: SubCategory of the task
          nullable: true
        additionalSubCategory:
          type: string
          description: Additional Subcategory for Verification Tasks
          nullable: true
        linkedApplicationEntityId:
          type: string
          description: Linked entity Id within the application
          nullable: true
        hold:
          allOf:
            - $ref: '#/components/schemas/fraudHold'
          description: Fraud hold details
          nullable: true
        state:
          type: string
          description: State of the task
        outcome:
          type: string
          description: Outcome of the task
          nullable: true
        createdDate:
          type: string
          description: Date when task was created
        updatedDate:
          type: string
          description: Date when task was updated
          nullable: true
        additionalDocumentsDetails:
          allOf:
            - $ref: '#/components/schemas/additionalDocumentsDetails'
          description: Additional Documents Details
          nullable: true
      additionalProperties: { }
      description: Model for Task data type in Get Task response
    updateTaskRequest:
      required:
        - applicationNumber
        - outcome
      type: object
      properties:
        applicationNumber:
          minLength: 1
          type: string
          description: Application Number
        outcome:
          minLength: 1
          type: string
          description: Outcome of the task
        additionalDocumentsDetails:
          allOf:
            - $ref: '#/components/schemas/additionalDocumentsDetails'
          description: Additional Document Details
          nullable: true
      additionalProperties: { }
      description: Request model for updating task
    xUserIdType:
      maxLength: 11
      pattern: ^application|cif$
      enum:
        - application
        - cif
      type: string
  parameters:
    applicationNumberQuery:
      name: applicationNumber
      in: query
      description: Application number
      schema:
        type: string
    xRequestIdHeader:
      name: x-request-id
      in: header
      required: true
      schema:
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        type: string
        description: Must be in UUID v4 format.
        format: uuid
    xStaffIdHeader:
      name: x-staff-id
      in: header
      schema:
        maxLength: 10
        pattern: '^[0-9]{1,10}$'
        type: string
        format: string
    xUserIdHeader:
      name: x-user-id
      in: header
      schema:
        maxLength: 10
        pattern: '^[0-9]{1,10}$'
        type: string
        format: string
    xUserIdTypeHeader:
      name: x-user-id-type
      in: header
      schema:
        $ref: '#/components/schemas/xUserIdType'
  securitySchemes:
    OAuth2:
      type: oauth2
      description: OAuth2 Client Credentials Grant Authorization
      flows:
        clientCredentials:
          tokenUrl: https://abc.com/idp/token.oauth2
          scopes:
            application-tasks.create: application-tasks.create
            application-tasks.update: application-tasks.update
            application-tasks.read: application-tasks.read
            application-tasks.cancel: application-tasks.cancel
security:
  - OAuth2: [ ]
tags:
  - name: create-tasks
    description: Creates a list of tasks for a given application
  - name: get-tasks
    description: Retrieves a list of tasks of a given application
  - name: update-task
    description: Updates a task for a given application
  - name: complete-verification
    description: Complete verification for a given application.
  - name: cancel-tasks
    description: Cancels tasks for a given application.
  - name: delete-task
    description: Deletes an existing task for a given an application id.
