openapi: 3.0.0
info:
  title: Order BFF
  description: Sample Order BFF
  version: '6.0'
  contact:
    email: devs@specmatic.io
servers:
  - url: http://localhost:8080
tags:
  - name: WIP
    description: API still under development
  - name: Product
    description: Product Related APIs
  - name: Order
    description: Order Related APIs
  - name: Monitor
    description: Monitor Related APIs
paths:
  /products:
    summary: Create a new product
    post:
      description: Create a new product
      operationId: createProduct
      tags:
        - Product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/ExtendedProductBase'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/Id'
        '202':
          description: Product Accepted
          headers:
            Link:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/MonitorLink'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
  /findAvailableProducts:
    parameters:
      - schema:
          $ref : '../../common/openapi/common-schemas.yaml#/components/schemas/ProductType'
        name: type
        in: query
        required: false
      - name: pageSize
        in: header
        schema:
          type: integer
        required: true
      - name: from-date
        in: query
        schema:
          type: string
          format: date
        required: true
        description: Filter products created from this date
      - name: to-date
        in: query
        schema:
          type: string
          format: date
        required: true
        description: Filter products created by this date
    get:
      description: Find available products
      operationId: findAvailableProducts
      tags:
        - Product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/ExtendedProduct'
        '429':
          description: TooManyRequests
          headers:
            Retry-After:
              schema:
                type: integer
                description: The number of seconds to wait before making the next request
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
  /orders:
    post:
      description: Create a new order
      operationId: createOrder
      tags:
        - Order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/OrderBase'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/Id'
        '202':
          description: Order accepted
          headers:
            Link:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/MonitorLink'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
    get:
      description: Retrieve orders
      operationId: getOrders
      tags:
        - WIP
        - Order
      parameters:
        - in: query
          name: orderId
          schema:
            type: integer
          required: false
          description: ID of the order to retrieve. If not provided, returns all orders.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/Order'
  /monitor/{id}:
    $ref: '../../common/openapi/common-schemas.yaml#/components/pathItems/MonitorById'
components:
  schemas:
    Product:
      $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/ExtendedProduct'
