openapi: 3.0.0
info:
  title: Resiliency Testing BFF
  description: Lab contract for graceful 429 and 202 responses
  version: '6.0'
  contact:
    email: devs@specmatic.io
servers:
  - url: http://localhost:8080
tags:
  - name: Product
    description: Product related APIs
  - name: Monitor
    description: Monitor APIs
paths:
  /products:
    summary: Create a new product
    post:
      description: Create a new product
      operationId: createProduct
      tags:
        - Product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/ProductBase'
            examples:
              SUCCESS_PRODUCT:
                value:
                  name: iPhone
                  type: gadget
                  inventory: 100
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/Id'
              examples:
                SUCCESS_PRODUCT:
                  value:
                    id: 1
        '202':
          description: Product Accepted
          headers:
            Link:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/MonitorLink'
            Retry-After:
              schema:
                type: integer
                description: The number of seconds to wait before polling the monitor link
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
  /findAvailableProducts:
    parameters:
      - schema:
          $ref : '../../common/openapi/common-schemas.yaml#/components/schemas/ProductType'
        name: type
        in: query
        required: false
        examples:
          SUCCESS_GET:
            value: gadget
      - name: pageSize
        in: header
        schema:
          type: integer
        required: true
        examples:
          SUCCESS_GET:
            value: 10
      - name: from-date
        in: query
        schema:
          type: string
          format: date
        required: true
        description: Filter products created from this date
        examples:
          SUCCESS_GET:
            value: "2025-01-01"
      - name: to-date
        in: query
        schema:
          type: string
          format: date
        required: true
        description: Filter products created by this date
        examples:
          SUCCESS_GET:
            value: "2025-11-28"
    get:
      description: Find available products
      operationId: findAvailableProducts
      tags:
        - Product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/Product'
              examples:
                SUCCESS_GET:
                  value:
                    - name: iPhone
                      id: 1
                      type: gadget
                      inventory: 100
                      createdOn: "2024-01-01"
        '429':
          description: TooManyRequests
          headers:
            Retry-After:
              schema:
                type: integer
                description: The number of seconds to wait before making the next request
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
  /monitor/{id}:
    get:
      description: Retrieves a Monitor by ID
      operationId: retrieveMonitor
      tags:
        - Monitor
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Monitor status
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/MonitorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../../common/openapi/common-schemas.yaml#/components/schemas/BadRequest'
